Feature/multiple sheet import and pageable adjustment on export
cleverpine/cp-excel-data-sync pull request #10
Opened 2024-02-12 13:55 UTC by rhrashev

2024-02-12 14:46 UTC, plamen-velikov requested changes

2024-02-12 14:46 UTC, plamen-velikov commented on src/main/java/com/cleverpine/exceldatasync/service/impl/read/ExcelImportServiceImpl.java
> +    public <Dto extends ExcelDto> void importFrom(Workbook workbook, Class<Dto> dtoClass, ExcelImportConfig config,
Define this either as private a method

2024-02-12 14:46 UTC, plamen-velikov commented on src/main/java/com/cleverpine/exceldatasync/service/impl/read/ExcelImportServiceImpl.java
> +            if (config == null || config.getSheets() == null || config.getSheets().isEmpty()) {
Does it make sense to do this before creating a workbook?
Also, it would be handy to log a message in this case I think -> some warning would be enough

2024-02-12 14:46 UTC, plamen-velikov commented on src/main/java/com/cleverpine/exceldatasync/service/impl/read/ExcelSheetImportConfig.java
> +    private final ExcelImportConfig config;
I would suggest adding a default implementation of this -> as a consumer you might be satisfied with the default case and  having to create smaller `ExcelSheetImportConfig` is better

2024-02-12 14:46 UTC, plamen-velikov commented on src/main/java/com/cleverpine/exceldatasync/service/api/read/ExcelImportService.java
>      <Dto extends ExcelDto> void importFrom(InputStream inputStream, Class<Dto> dtoClass, ExcelImportConfig config, Consumer<List<Dto>> batchConsumer);
We could change this to get a single `ExcelSheetImportConfig`
or 
A different approach to this is to only grab the DtoClass and the consumer and put those into a method 
Atleast, for now I don't see how we can utilize ExcelImportConfig to be different for different dtos in the excel. 

Also, I would suggest the other method just to use List<ExcelSheetImportConfig> unless you see future improvements for multiple excelImportConfigs

2024-02-12 14:46 UTC, plamen-velikov commented on src/main/java/com/cleverpine/exceldatasync/service/impl/write/ExcelExportServiceImpl.java
> +import static com.cleverpine.exceldatasync.util.ExcelAnnotationHelper.*;
I suggest avoid * imports when possible. In intellij the * collapse is set way too low IMO

2024-02-12 14:46 UTC, plamen-velikov commented on src/main/java/com/cleverpine/exceldatasync/service/api/write/ExportPage.java
> +    boolean hasNext();
sounds a bit weird a Page to know if it hasNext, at least I understand that the Pageable object the one containing the pages so everything related to managing the pages should be there

2024-02-12 14:46 UTC, plamen-velikov commented on src/main/java/com/cleverpine/exceldatasync/service/impl/write/basic/BasicExportPageable.java
> +public class BasicExportPageable implements ExportPageable {
I wonder if it makes sense to change the Import to use the Pageable as well? In that case perhaps we should allow ourselves to make fewer changes in the future by making this common for both?

2024-02-12 14:46 UTC, plamen-velikov commented on src/test/java/ImportEmptyTests.java
> +                new ExcelMultipleImportConfig(List.of(new ExcelSheetImportConfig<>(NoHeadersDocumentDto.class, config, documents::addAll)));
just for the completeness shouldn't this have more than one Configs? Same for the rest of the tests for this functionality

2024-02-12 14:46 UTC, plamen-velikov commented on src/test/java/ImportOffsetTests.java
> +    void multipleImport_onSheetWithCustomCoordinates_shouldImportWithDefaultBatchSize() {
I would suggest adding a separate sheet that tests the multiple import with multiple ExcelSheetImportConfig

2024-02-12 14:46 UTC, plamen-velikov commented on src/test/java/MultipleImportMappingTests.java
> +public class MultipleImportMappingTests extends ImportTests {
Any difference from the other Mapping tests ?  If not perhaps there is no need for this 
Instead what I think we should add is a mapping to bigDecimal .. or perhaps I am not seeing it

2024-02-12 15:02 UTC, rhrashev commented on src/test/java/MultipleImportMappingTests.java
> +public class MultipleImportMappingTests extends ImportTests {
the only difference is the calling method, since I'm reusing parts of the single import, I am just testing that I haven't screwed anything up with the common code I am using

2024-02-12 15:09 UTC, rhrashev commented on src/main/java/com/cleverpine/exceldatasync/service/api/write/ExportPage.java
> +    boolean hasNext();
For me, the Pageable should only hold the page, size, maybe sort. And actually the Pageable cannot know if there is a next page, because you use the pageable to request the data. That is why the Page knows if there is data left, because it is the result of the retrieved data.

2024-02-12 15:12 UTC, rhrashev commented on src/main/java/com/cleverpine/exceldatasync/service/api/read/ExcelImportService.java
>      <Dto extends ExcelDto> void importFrom(InputStream inputStream, Class<Dto> dtoClass, ExcelImportConfig config, Consumer<List<Dto>> batchConsumer);
I like the idea of using a single ExcelSheetImport for the single import.
For the config implementation, I've only done it this way in order to be consistent with the export.

2024-02-12 15:17 UTC, rhrashev commented on src/main/java/com/cleverpine/exceldatasync/service/impl/read/ExcelSheetImportConfig.java
> +    private final ExcelImportConfig config;
There is already a ExcelImportConfigImpl

2024-02-12 15:32 UTC, rhrashev commented on src/main/java/com/cleverpine/exceldatasync/service/impl/write/basic/BasicExportPageable.java
> +public class BasicExportPageable implements ExportPageable {
maybe in a future feature

2024-02-13 08:35 UTC, plamen-velikov commented on src/main/java/com/cleverpine/exceldatasync/service/impl/read/ExcelSheetImportConfig.java
> +    private final ExcelImportConfig config;
What I meant is use it as a default implementation -> making the ExcelImportConfig optional, again I think the ExcelImportConfig should be a configuration per sheet not per dto as the ExcelSheetImportConfig represents that

2024-02-13 11:15 UTC, merged