Initial implementation of for reading Excel files.
cleverpine/cp-excel-data-sync pull request #2
Opened 2024-01-04 13:30 UTC by denislav-v

2024-01-05 08:30 UTC, plamen-velikov requested changes

2024-01-05 08:30 UTC, plamen-velikov commented on src/main/java/com/cleverpine/exceldatasync/util/ExcelValueMapper.java
> +                return true;
you could use the more simplified version here: 
return switch(binaryAnsswer) {
     case "Yes", "Ja" -> true;
     case "No" -> false;
     default -> nll;
};
I would say that this should be a custom mapper  same as BooleanToX

2024-01-05 08:30 UTC, plamen-velikov commented on src/main/java/com/cleverpine/exceldatasync/mapper/ExcelExportCustomMapper.java
> +// Maybe rename to ExcelCustomMapper -> as it will be used for import and export
may be apply this comment

2024-01-05 08:30 UTC, plamen-velikov commented on src/main/java/com/cleverpine/exceldatasync/util/ExcelValueMapper.java
> +public final class ExcelValueMapper {
does this class has to be public?

2024-01-05 08:30 UTC, plamen-velikov commented on src/main/java/com/cleverpine/exceldatasync/util/ExcelValueMapper.java
> +                Cell evaluatedCell = cell.getSheet().getWorkbook().getCreationHelper()
May be have a custom util function => evaluateInCell(cell) -> that does this.
I assume you will use the same thing in other places as well

2024-01-05 08:30 UTC, plamen-velikov commented on src/main/java/com/cleverpine/exceldatasync/util/ExcelValueMapper.java
> +                if (evaluatedCell.getCellType() == CellType.BOOLEAN) {
I wonder if recursive call wouldn't be cleaner -> 
return getBooleanValueFromCell(evaluated cell)

2024-01-05 08:30 UTC, plamen-velikov commented on src/main/java/com/cleverpine/exceldatasync/util/ExcelValueMapper.java
> +                    return Double.parseDouble(cell.getStringCellValue());
I would suggest a number util class that has different parsing functions -> 
parseDouble(Double value, Double default) -> you could have a overload here with default value = null

2024-01-05 08:30 UTC, plamen-velikov commented on src/main/java/com/cleverpine/exceldatasync/util/ExcelValueMapper.java
> +        return Map.of(
I think you can declare this directly when you define the field ( at least IMO it looks better)

2024-01-05 08:30 UTC, plamen-velikov commented on src/main/java/com/cleverpine/exceldatasync/service/impl/VarHandleCache.java
> +    private Field[] initializeFields(Class<?> dtoClass) {
do you need this method? 
I think the name suggest something that this method doesn't do.

2024-01-05 08:30 UTC, plamen-velikov commented on src/main/java/com/cleverpine/exceldatasync/service/impl/VarHandleCache.java
> +            var lookup = MethodHandles.privateLookupIn(dtoClass, MethodHandles.lookup());
I wonder if this is not more efficient to be called once. Right now it's implicitly in a loop .. so for each field you are creating this lookup again. Note this is just an assumption I haven't checked how the underline implementation works.

2024-01-05 08:30 UTC, plamen-velikov commented on src/main/java/com/cleverpine/exceldatasync/util/ExcelValueMapper.java
> +    public static <T> T createInstance(Class<T> aClass, String instanceName) {
I would suggest removing this instanceName -> it's used in the exception and it would be much more meaningful to have the simple class name which can be obtained via the aClass. 
this could also simplify this invocations:
MAPPER_CACHE.computeIfAbsent(excelMapperClass, key -> createInstance(key, Constants.MAPPER));

2024-01-05 08:30 UTC, plamen-velikov commented on src/main/java/com/cleverpine/exceldatasync/util/ExcelValueMapper.java
> +    public static String getMapperValue(Object obj, Field field) throws Exception {
I find this method having a misleading name: 
doing a Boolean to String conversion implicitly.

2024-01-05 14:18 UTC, denislav-v commented on .gitignore
> +/src/test/
I did not commit them, because they depend on a 90+ MB Excel file.

2024-01-05 14:19 UTC, denislav-v commented on src/main/java/com/cleverpine/exceldatasync/annotations/ExcelColumn.java
> +public @interface ExcelColumn {
We'll be done in the next PR (this one is just import functionality, next will be update annotations.)

2024-01-05 14:40 UTC, plamen-velikov commented on .gitignore
> +/src/test/
That should be fine in my opinion as we want tests for this anyway so unless there is a limit I don't see and issue.

2024-01-07 11:28 UTC, denislav-v commented on src/main/java/com/cleverpine/exceldatasync/util/ExcelValueMapper.java
> +public final class ExcelValueMapper {
I think normally Utility classes are public final, unless you mean something different.

2024-01-07 12:05 UTC, denislav-v commented on src/main/java/com/cleverpine/exceldatasync/util/ExcelValueMapper.java
> +                    return Double.parseDouble(cell.getStringCellValue());
Here I came up with a new idea to have ExcelCellParsingHelper.class, with a few more methods that do similar things.

2024-01-07 12:12 UTC, denislav-v commented on src/main/java/com/cleverpine/exceldatasync/util/ExcelValueMapper.java
> +    public static String getMapperValue(Object obj, Field field) throws Exception {
I think you are right, however this method is bot being used anywhere in the code (it's leftover from previous app skeleton). I will delete in out for now, we'll see how to include it in the import.

2024-01-08 10:34 UTC, plamen-velikov approved these changes

2024-01-08 11:19 UTC, merged